import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const contracts = ["SmartIrsEngine.sol", "ERC20.sol"]
const __dirname = path.dirname(fileURLToPath(import.meta.url));

function findFoundryRoot(startPath) {
    let current = path.resolve(startPath);
    const root = path.parse(current).root;

    while (current !== root) {
        if (fs.existsSync(path.join(current, "foundry.toml"))) {
            return current;
        }
        current = path.dirname(current);
    }

    return null;
}

const projectRoot = findFoundryRoot(__dirname);

if (!projectRoot) {
    console.error("Error: Could not find 'foundry.toml'. Make sure this script is run inside a Foundry project.");
    process.exit(1);
}

const outDir = path.join(projectRoot, "out");
const abiDir = path.join(projectRoot, "abis");

if (!fs.existsSync(outDir)) {
    console.error("Error: 'out/' directory not found in project root. Run 'forge build' in the Foundry project root first.");
    process.exit(1);
}

// Create abis directory if it doesn't exist
if (!fs.existsSync(abiDir)) {
    fs.mkdirSync(abiDir, { recursive: true });
    console.log(`Created directory: ${abiDir}`);
}

// Optional: Add a header comment to each generated file
const headerComment = `// This file is auto-generated by extractAbis.js
// Do not edit manually — re-run the script after forge build\n\n`;

// Walk through each .sol directory in out/
fs.readdirSync(outDir).forEach((item) => {
    const itemPath = path.join(outDir, item);
    if (!fs.statSync(itemPath).isDirectory() || !contracts.includes(item)) {
        return;
    }

    // Inside each .sol folder
    fs.readdirSync(itemPath).forEach((file) => {
        if (file.endsWith(".json") && !file.endsWith(".dbg.json")) {
            const artifactPath = path.join(itemPath, file);
            const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

            // Only process files that have a valid ABI array
            if (artifact.abi && Array.isArray(artifact.abi)) {
                const contractName = path.basename(file, ".json");
                const abiOutputPath = path.join(abiDir, `${contractName}Abi.ts`);

                const abiJson = JSON.stringify(artifact.abi, null, 2);
                const content = `${headerComment}export const ${contractName}Abi = ${abiJson} as const;\n`;

                fs.writeFileSync(abiOutputPath, content);
                console.log(`Saved ABI: ${contractName}Abi.ts`);
            }
        }
    });
});

console.log("ABI extraction complete!");